language: node_js
node_js:
  - 14
python:
  # PyPy versions
  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - echo requirements installed
  - cd Code/backend
  - echo "installing"
  - npm install nodemailer
  - npm install
  - npx nodemon &
script:
  - cd test
  - pytest
  

